Sprint2
microservices-course-itmo/am-parser-service pull request #13
Opened 2020-10-05 17:51 UTC by HappyLiner

2020-10-07 19:50 UTC, shinehlina requested changes
В целом лайк. За исключением каких-то stub классов (не очень для меня понятных)

2020-10-07 19:50 UTC, shinehlina commented on profiles/am-parser-service.yml
> +    image: am-parser-service:0.1.0-SNAPSHOT
Версию в помнике апните

2020-10-07 19:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmCatalogServiceStub.java
> +public class AmCatalogServiceStub implements AmCatalogService {
Это что такое?

2020-10-07 19:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceStub.java
>  public class AmParserServiceStub implements AmParserService {
Что это вообще за stub классы?

2020-10-07 19:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmServiceStub.java
> +public class AmServiceStub implements AmService {
И вот это что такое?

2020-10-07 19:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceStub.java
>  public class AmWineServiceStub implements AmWineService {
?

2020-10-07 19:50 UTC, shinehlina commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "spring.version.name",
Что это вообще за файл?

2020-10-07 19:50 UTC, shinehlina commented on src/main/resources/application.properties
> +job.cron.update.repository=0 0 4 * * *
Напишите, что это значит

2020-10-07 19:50 UTC, shinehlina commented on src/test/java/com/wine/to/up/am/parser/service/service/impl/AmCatalogServiceImplTest.java
> +        amCatalogService.updateCatalog(amCatalogService.getCatalog(amClient.getMainPage()));
Сделайте так, чтобы тест что-то проверял. То есть как минимум в конце должны быть какие-то ассерты (короче посмотрите, как тесты писать)

2020-10-08 08:26 UTC, HappyLiner commented on src/main/resources/application.properties
> +job.cron.update.repository=0 0 4 * * *
Это cron для `UpdateRepositoryJob` класса. Срабатывает каждый день в 04:00

2020-10-08 08:32 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmCatalogServiceStub.java
> +public class AmCatalogServiceStub implements AmCatalogService {
Stub классы являются заглушками, реализуемыми в первую очередь после создания интерфейса, чтобы можно было разрабатывать сервисы, использующие данные интерфейсы, до написания классов, реализующих эти самые интерфейсы

2020-10-08 08:33 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceStub.java
>  public class AmParserServiceStub implements AmParserService {
Stub классы являются заглушками, реализуемыми в первую очередь после создания интерфейса, чтобы можно было разрабатывать сервисы, использующие данные интерфейсы, до написания классов, реализующих эти самые интерфейсы

2020-10-08 08:33 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmServiceStub.java
> +public class AmServiceStub implements AmService {
Stub классы являются заглушками, реализуемыми в первую очередь после создания интерфейса, чтобы можно было разрабатывать сервисы, использующие данные интерфейсы, до написания классов, реализующих эти самые интерфейсы

2020-10-08 08:33 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceStub.java
>  public class AmWineServiceStub implements AmWineService {
Stub классы являются заглушками, реализуемыми в первую очередь после создания интерфейса, чтобы можно было разрабатывать сервисы, использующие данные интерфейсы, до написания классов, реализующих эти самые интерфейсы

2020-10-08 08:37 UTC, HappyLiner commented on profiles/am-parser-service.yml
> +    image: am-parser-service:0.1.0-SNAPSHOT
Апнули

2020-10-08 09:03 UTC, SSyrova commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "spring.version.name",
Дополнительные метаданные, это только для удобства работы с application.properties в IDE, если это не надо, можно не делать. В файле перечислены все допустимые свойства для приложения.

2020-10-08 09:04 UTC, SSyrova commented on src/test/java/com/wine/to/up/am/parser/service/service/impl/AmCatalogServiceImplTest.java
> +        amCatalogService.updateCatalog(amCatalogService.getCatalog(amClient.getMainPage()));
Данный тест был написан исключительно для показа работы кода. В дальнейшем, он будет переписан на нормальный  unit-test

2020-10-10 22:24 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceStub.java
>  public class AmParserServiceStub implements AmParserService {
Но ведь у вас уже есть реализация. Например, для этого интерфейса - AmParserServiceImpl. Зачем они вам сейчас, если классы уже есть, лучше удалить

2020-10-10 22:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmServiceStub.java
> +public class AmServiceStub implements AmService {
Написала выше

2020-10-10 22:27 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceStub.java
>  public class AmWineServiceStub implements AmWineService {
Написала выше

2020-10-10 22:28 UTC, shinehlina commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceStub.java
>  public class AmWineServiceStub implements AmWineService {
А, не заметила, такого нет

2020-10-10 22:29 UTC, shinehlina commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "spring.version.name",
А, в целом норм)

2020-10-10 22:31 UTC, shinehlina commented on src/main/resources/application.properties
> +job.cron.update.repository=0 0 4 * * *
Я имела ввиду коммент над самим свойством) Мне кажется, что это стоит объяснить, чтобы не пришлось расшифровывать

2020-10-10 22:52 UTC, shinehlina commented on src/test/java/com/wine/to/up/am/parser/service/service/impl/AmCatalogServiceImplTest.java
> +        amCatalogService.updateCatalog(amCatalogService.getCatalog(amClient.getMainPage()));
Вообще, насколько я знаю, вам на 3 спринт нужно написать тесты. Так что мы вы можете закончить его и добавить. Мне это не очень нравится 

Плюс когда вы будете писать, сделайте так, чтобы тесты не пытались обратиться к базе. Это не прикольно. Используйте какую-нибудь in memory штуку.

2020-10-10 22:54 UTC, shinehlina requested changes
Поправьте конверсейшены

2020-10-10 22:59 UTC, Anglopol reviewed
Как обычно все круто, вы прям молодцы большие
Уберите ненужные стабы, поправьте тесты и небольшое описание для крона сделайте, после чего будем мерджить

2020-10-11 15:13 UTC, shinehlina approved these changes

2020-10-11 22:08 UTC, Anglopol approved these changes

2020-10-12 08:11 UTC, merged