Base classes for the Scheduled update
microservices-course-itmo/am-parser-service pull request #2
Opened 2020-09-28 19:08 UTC by OlegDF

2020-09-28 22:53 UTC, HappyLiner requested changes

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/scheduledupdate/ScheduledUpdater.java
> +    WineRepository wineRepository;
Всегда указывай модификатор доступа

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/scheduledupdate/ScheduledUpdater.java
> +public class ScheduledUpdater {
Название класса не объясняет его суть, лучше переименовать в `ActualizeWineJob`

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/scheduledupdate/ScheduledUpdater.java
> +    @Scheduled(cron = "0 0 1 * * MON")
Лучше вынести cron в `application.properties` с названием `job.cron.actualize.wine`, а здесь оставить `@Scheduled(cron = "${job.cron.actualize.wine}")`

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/scheduledupdate/ScheduledUpdater.java
> +                    if(!newWine.equals(oldWine)) {
Это условие всегда будет возвращать false

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/scheduledupdate/ScheduledUpdater.java
> +            }
Глубокая вложенность. Старайся использовать не более 3-х вложенных блоков в методе

2020-09-28 22:53 UTC, HappyLiner commented on src/main/java/com/wine/to/up/am/parser/service/parse/Parser.java
> +public class Parser {
Зачем нужен этот класс?

2020-09-29 16:57 UTC, OlegDF commented
Parser - заглушка, другому человеку поручили написать собственно парсер, который бы возвращал актуальный список вин с сайта, и такой список нужен в этом классе

2020-10-05 13:49 UTC, HappyLiner commented
Подтяни все изменения из sprint2, убери все конфликты если они будут, сделай всё, что написано в trello по этой задаче, и назначь PR в `sprint2`

2020-10-05 13:50 UTC, closed without merging