Sprint1 Pull Request
microservices-course-itmo/am-parser-service pull request #5
Opened 2020-09-30 03:53 UTC by SSyrova

2020-10-04 11:47 UTC, Anglopol requested changes
Возьмите, пожалуйста, последний помник из демо-сервиса, в остальном никаких замечаний

2020-10-04 11:47 UTC, Anglopol commented on pom.xml
> +        <dependency>
А для чего вы используете данную зависимость? Не особо понимаю

2020-10-04 14:08 UTC, SSyrova commented on pom.xml
> +        <dependency>
**spring-boot-configuration-processor** - это процессор аннотаций для обеспечения автозаполнения и документации для свойств при редактировании файлов application.properties

2020-10-05 11:30 UTC, AfanasievYuriy approved these changes
Тут по мелочи - можете в след. пр поправить

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmClientStub.java
> +                    .connect("https://amwine.ru/catalog/vino/")
Весь хардкод вынесите в константы

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmClientStub.java
> +public class AmClientStub implements AmClient {
док на класс добавьте. 
мне вот, например, не понтяно, почему он Stub называется

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceImpl.java
> +    private static final ObjectMapper mapper = new ObjectMapper();
этот мапер можно через конфигурацию сделать бином @Bean (там же можно его и сконфигурить) и инжектить в остальные компоненты в качетсве зависимости

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmClientStub.java
> +            e.printStackTrace();
пологируйте

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceStub.java
> +        return 457L;
в констатнты

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceImpl.java
> +    private AmClient client;
раз уж начали, инжектите зависимости через конструктор и дальше

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceImpl.java
> +    public List<WineDto> getAllAmWines() {
док

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceImpl.java
> +    public Long getCatalogPagesAmount() {
док

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmParserServiceImpl.java
> +    public List<WineDto> parsePage(Document document) {
док

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmWineServiceImpl.java
> +            /*
не понял- это что значит?)

всмысле почему здесь просто секция с комментариями?

2020-10-05 11:30 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/am/parser/service/service/impl/AmClientStub.java
> +                    .connect("https://amwine.ru/catalog/vino/")
UPD
А почему не попользовались пропертями? у вас же в application.properties есть эти значения

2020-10-05 11:32 UTC, Anglopol commented
Ребят, дадим аппрув на мердж сразу после того как помник обновите, остальное мелочи

2020-10-05 11:35 UTC, AfanasievYuriy requested changes
обновите помник, ага

2020-10-05 13:50 UTC, Anglopol approved these changes

2020-10-05 13:53 UTC, shinehlina approved these changes

2020-10-05 13:54 UTC, merged